[package]
name = "deq example"
version = "0.1.0"
authors = ["Lukas Krickl <lukas@krickl.dev>"]
description = "Deq example"
license = "MIT"
homepage = "https://github.com/unlink2/deq"

[[bin]]
name = "example"
path = "src/main.rs"

[dependencies]
deq = {path = "../lib"}
