[package]
name = "deq_core"
version = "0.1.5"
authors = ["Lukas Krickl <lukas@krickl.dev>"]
description = "Deq core"
license = "MIT"
homepage = "https://github.com/unlink2/deq"

[lib]
name = "deq_core"
path = "src/lib.rs"

[dependencies]
