[package]
name = "deq_macros"
version = "0.1.0"
authors = ["Lukas Krickl <lukas@krickl.dev>"]

[lib]
name = "deq_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
deq_core = {path = "../core"}
